# Generated by Django 6.1 on 2026-09-02 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('cancha', 'fecha', 'hora_inicio'), name='reserva_cancha_fecha_hora_unicas'),
        ),
    ]
