# Generated by Django 6.1 on 2026-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_reserva_cancha_fecha_hora_unicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
