# Generated by Django 6.1 on 2026-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_mercadopago_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20),
        ),
    ]
