# Generated by Django 6.1 on 2026-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
