# Generated by Django 6.1 on 2026-09-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_a', models.CharField(max_length=100)),
                ('equipo_b', models.CharField(max_length=100)),
                ('goles_a', models.IntegerField(default=0)),
                ('goles_b', models.IntegerField(default=0)),
                ('mvp_partido', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_partido', to='reservas.reserva')),
            ],
        ),
    ]
