# Generated by Django 6.1 on 2026-09-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_perfilcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icono', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='cancha',
            name='calzado_permitido',
            field=models.CharField(default='Multitaco / Zapatillas de baby fútbol. No tapones de aluminio', max_length=180),
        ),
        migrations.AddField(
            model_name='cancha',
            name='es_techada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='formato_juego',
            field=models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('futbol_11', 'Fútbol 11')], default='futbol_5', max_length=20),
        ),
        migrations.AddField(
            model_name='cancha',
            name='iluminacion_led',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_estacionamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_quincho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_tribunas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_vestuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tiene_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_superficie',
            field=models.CharField(choices=[('sintetico_fifa', 'Pasto Sintético FIFA Quality'), ('natural', 'Pasto Natural'), ('parquet_pista', 'Parquet/Pista')], default='sintetico_fifa', max_length=30),
        ),
        migrations.CreateModel(
            name='ResenaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jugador', models.CharField(max_length=120)),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='reservas.cancha')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios_adicionales',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='reservas.servicioadicional'),
        ),
    ]
