# Generated by Django 6.1 on 2026-09-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_servicioadicional_cancha_calificacion_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenacancha',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
