# Generated by Django 6.1 on 2026-09-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_resenacancha_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='partidos/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='reservas.resultadopartido')),
            ],
        ),
    ]
